name: model-wine-quality
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: iterative/setup-cml@v2.0.1
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          python train.py
          
          echo "## Model metrics" > report.md
          cat metrics.txt >> report.md
          
          echo "## Data viz" >> report.md
          echo '![](./feature_importance.png "feature importance")' >> report.md
          echo '![](./residuals.png "feature importance")' >> report.md
          
          cml comment create report.md
